uploads = []

[[generated]]
id = "iwJlWpgT0MMTEcLRybc7Q"
uri = "file://artifacts/portfolio/public/avatar.png"
type = "image"
title = "Avatar of a young male developer"

[[outputs]]
id = "L8SnT1smuy04t2M0vqd5g"
uri = "file://jay-chafekar-portfolio.zip"
type = "unspecified"
title = "Jay Chafekar – Portfolio Source Code"
